language: php

matrix:
  include:
  - php: '7.0'
  - php: '7.1'
  - php: '7.2'
  - php: '7.2'
    env: deps=high
  - php: '7.3'
  - php: '7.3'
    env: deps=high
  - php: '7.4'
    env: deps=high
  - php: 'nightly'
  fast_finish: true
  allow_failures:
  - php: nightly

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update
  - composer --version

before_script:
  - if [ -z "$deps" ]; then composer install $composer; fi;
  - if [ "$deps" = "low" ]; then composer update --prefer-lowest -n $composer; fi;
  - if [ "$deps" = "high" ]; then composer update -n $composer; fi;

script:
  - >
    echo;
    echo "Running tests";
    SYMFONY_PHPUNIT_REMOVE_RETURN_TYPEHINT=1 vendor/bin/simple-phpunit --colors
  - >
    echo;
    echo "Running PHP lint";
    find . -name \*.php ! -path './vendor/*' | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;
